
TARGET_FLAGS=$(CC_SHARED) -DRegisterArc=DllRegisterArc -DRegisterCodec=DllRegisterCodec

include ../../../../makefile.crc32
include ../../../../makefile.machine

LOCAL_LINK=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS_DLL)

include ../../../../makefile.glb

