/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stardust_autojs_runtime_api_SevenZip */

#ifndef _Included_com_stardust_autojs_runtime_api_SevenZip
#define _Included_com_stardust_autojs_runtime_api_SevenZip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stardust_autojs_runtime_api_SevenZip
 * Method:    cmd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_stardust_autojs_runtime_api_SevenZip_cmdExec
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
